<?php

namespace App\Services\Sales;

use App\Exceptions\ApiException;
use App\Models\Tenant\ProformaInvoice;
use App\Models\Tenant\SalesOrder;
use App\Models\Tenant\SalesQuotation;
use App\Services\Audit\AuditLogService;
use App\Services\DocumentNumbering\DocumentNumberService;
use App\Services\Sales\Concerns\HandlesSalesDocuments;
use App\Services\Tenant\TenantContext;
use App\Support\DocumentNumbering\DocumentType;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;

class ProformaInvoiceService
{
    use HandlesSalesDocuments;

    public function __construct(private readonly TenantContext $tenantContext, private readonly DocumentNumberService $documentNumberService, private readonly SalesCalculationService $calculationService, private readonly ?AuditLogService $auditLogService = null) {}
    public function list(array $filters = []): Collection { $q = ProformaInvoice::query()->with('customer'); if (! empty($filters['status'])) $q->where('status', (string) $filters['status']); return $q->orderByDesc('proforma_date')->orderByDesc('id')->get(); }
    public function find(int $id): ProformaInvoice { return ProformaInvoice::query()->with('lines.product', 'customer', 'quotation', 'salesOrder')->findOrFail($id); }
    public function create(array $data): ProformaInvoice { $company = $this->tenantContext->company(); if (! $company) throw ApiException::make('COMPANY_NOT_FOUND', 'Company context not resolved.', 422); $this->ensureCustomerExists((int) $data['customer_id']); return DB::connection('tenant')->transaction(function () use ($company, $data) { $lines = $this->normalizeLines((array) $data['lines']); $totals = $this->calculationService->calculateDocument($lines, $data); $headerTotals = $totals; unset($headerTotals['lines']); $proforma = ProformaInvoice::query()->create(array_merge($this->guardedForHeader($data), $headerTotals, ['proforma_number' => $this->documentNumberService->generate($company, DocumentType::PROFORMA_INVOICE, (string) $data['proforma_date']), 'status' => 'draft', 'created_by' => auth()->id(), 'updated_by' => auth()->id()])); $proforma->lines()->createMany($totals['lines']); return $proforma->refresh()->load('lines', 'customer'); }); }
    public function update(ProformaInvoice $proforma, array $data): ProformaInvoice { if ($proforma->status !== 'draft') throw ApiException::make('PROFORMA_NOT_EDITABLE', 'Proforma status is not editable.', 422); return DB::connection('tenant')->transaction(function () use ($proforma, $data) { $lines = $this->normalizeLines((array) ($data['lines'] ?? $proforma->lines()->get()->toArray())); $totals = $this->calculationService->calculateDocument($lines, array_merge($proforma->toArray(), $data)); $headerTotals = $totals; unset($headerTotals['lines']); $proforma->fill(array_merge($this->guardedForHeader($data), $headerTotals, ['updated_by' => auth()->id(), 'revision_no' => (int) $proforma->revision_no + 1]))->save(); $proforma->lines()->delete(); $proforma->lines()->createMany($totals['lines']); return $proforma->refresh()->load('lines', 'customer'); }); }
    public function createFromQuotation(SalesQuotation $quotation, array $overrides = []): ProformaInvoice { $this->guardConvertibleSource($quotation->status, 'sales quotation'); $quotation->loadMissing('lines'); return $this->create(array_merge(['proforma_date' => now()->toDateString(), 'valid_until' => $quotation->valid_until?->toDateString(), 'customer_id' => $quotation->customer_id, 'customer_address' => $quotation->customer_address, 'sales_quotation_id' => $quotation->id, 'salesperson_id' => $quotation->salesperson_id, 'currency_code' => $quotation->currency_code, 'exchange_rate' => $quotation->exchange_rate, 'is_taxable' => $quotation->is_taxable, 'tax_included' => $quotation->tax_included, 'header_discount_type' => $quotation->header_discount_type, 'header_discount_value' => $quotation->header_discount_value, 'source_type' => 'sales_quotation', 'source_id' => $quotation->id, 'source_number' => $quotation->quotation_number, 'source_revision' => $quotation->revision_no, 'lines' => $quotation->lines->map(fn ($line) => array_merge($line->only(['product_id','product_code','description','quantity','unit_id','unit_price','discount_type','discount_value','tax_id','tax_rate','warehouse_id','department_id','project_id','sort_order','metadata']), ['source_line_type' => 'sales_quotation_line', 'source_line_id' => $line->id]))->toArray()], $overrides)); }
    public function createFromSalesOrder(SalesOrder $salesOrder, array $overrides = []): ProformaInvoice { $this->guardConvertibleSource($salesOrder->status, 'sales order'); $salesOrder->loadMissing('lines'); return $this->create(array_merge(['proforma_date' => now()->toDateString(), 'customer_id' => $salesOrder->customer_id, 'customer_address' => $salesOrder->customer_address, 'sales_order_id' => $salesOrder->id, 'salesperson_id' => $salesOrder->salesperson_id, 'currency_code' => $salesOrder->currency_code, 'exchange_rate' => $salesOrder->exchange_rate, 'is_taxable' => $salesOrder->is_taxable, 'tax_included' => $salesOrder->tax_included, 'header_discount_type' => $salesOrder->header_discount_type, 'header_discount_value' => $salesOrder->header_discount_value, 'source_type' => 'sales_order', 'source_id' => $salesOrder->id, 'source_number' => $salesOrder->order_number, 'source_revision' => $salesOrder->revision_no, 'lines' => $salesOrder->lines->map(fn ($line) => array_merge($line->only(['product_id','product_code','description','quantity','unit_id','unit_price','discount_type','discount_value','tax_id','tax_rate','warehouse_id','department_id','project_id','sort_order','metadata']), ['source_line_type' => 'sales_order_line', 'source_line_id' => $line->id]))->toArray()], $overrides)); }
    public function issue(ProformaInvoice $proforma): ProformaInvoice { return $this->transition($proforma, 'issued', 'issued_by', 'issued_at', ['draft']); }
    public function accept(ProformaInvoice $proforma): ProformaInvoice { return $this->transition($proforma, 'accepted', 'accepted_by', 'accepted_at', ['issued']); }
    public function cancel(ProformaInvoice $proforma, ?string $reason = null): ProformaInvoice { $proforma->cancel_reason = $reason; return $this->transition($proforma, 'cancelled', 'cancelled_by', 'cancelled_at', ['draft', 'issued']); }
    public function markConverted(ProformaInvoice $proforma): ProformaInvoice { return $this->transition($proforma, 'converted', 'converted_by', 'converted_at', ['issued', 'accepted']); }
    private function transition(ProformaInvoice $proforma, string $status, string $userField, string $dateField, array $from): ProformaInvoice { if (! in_array($proforma->status, $from, true)) throw ApiException::make('INVALID_PROFORMA_STATUS', 'Invalid proforma status transition.', 422); $proforma->status = $status; $proforma->{$userField} = auth()->id(); $proforma->{$dateField} = now(); $proforma->save(); return $proforma->refresh()->load('lines', 'customer'); }
    private function guardConvertibleSource(string $status, string $source): void { if (in_array($status, ['cancelled', 'rejected', 'converted', 'void', 'closed'], true)) throw ApiException::make('SOURCE_NOT_CONVERTIBLE', ucfirst($source).' is not available for conversion.', 422); }
}
