<?php

return [
    'permissions' => [
        // Dashboard
        'dashboard.view',

        // Settings
        'settings.company.view',
        'settings.company.edit',
        'settings.users.view',
        'settings.users.manage',
        'settings.permissions.view',
        'settings.permissions.manage',

        // Master Data
        'master_data.view',
        'master_data.manage',
        'coa.view',
        'coa.create',
        'coa.edit',
        'coa.deactivate',
        'contacts.view',
        'contacts.create',
        'contacts.edit',
        'contacts.deactivate',
        'products.view',
        'products.create',
        'products.edit',
        'products.deactivate',
        'units.view',
        'units.create',
        'units.edit',
        'units.deactivate',
        'warehouses.view',
        'warehouses.create',
        'warehouses.edit',
        'warehouses.deactivate',
        'departments.view',
        'departments.create',
        'departments.edit',
        'departments.deactivate',
        'projects.view',
        'projects.create',
        'projects.edit',
        'projects.deactivate',

        // Journal
        'journal.view',
        'journal.create',
        'journal.edit',
        'journal.void',
        'journal.approve',
        'journal.post',

        // Sales
        'sales.view',
        'sales.create',
        'sales.edit',
        'sales.void',
        'sales.approve',
        'sales.post',

        // Purchase
        'purchase.view',
        'purchase.create',
        'purchase.edit',
        'purchase.void',
        'purchase.approve',
        'purchase.post',

        // Cash Bank
        'cash_bank.view',
        'cash_bank.create',
        'cash_bank.edit',
        'cash_bank.void',
        'cash_bank.approve',
        'cash_bank.post',
        'cash_bank.transfer',

        // Inventory
        'inventory.view',
        'inventory.manage',
        'inventory.adjustment.create',
        'inventory.adjustment.edit',
        'inventory.adjustment.void',
        'inventory.transfer',
        'inventory.stock_opname',

        // Reports
        'reports.view',
        'reports.export',

        // Fiscal year closing / locking
        'fiscal_year.view',
        'fiscal_year.close',
        'fiscal_year.reopen',
        'fiscal_year.lock_override',

        // Audit
        'audit.view',
    ],

    'roles' => [
        'owner' => ['*'],
        'admin' => ['*'],
        'finance' => [
            'dashboard.view',
            'settings.company.view',
            'master_data.view',
            'coa.view',
            'coa.create',
            'coa.edit',
            'contacts.view',
            'contacts.create',
            'contacts.edit',
            'departments.view',
            'projects.view',
            'journal.view',
            'journal.create',
            'journal.edit',
            'journal.void',
            'journal.approve',
            'journal.post',
            'cash_bank.view',
            'cash_bank.create',
            'cash_bank.edit',
            'cash_bank.void',
            'cash_bank.approve',
            'cash_bank.post',
            'cash_bank.transfer',
            'reports.view',
            'reports.export',
            'audit.view',
            'fiscal_year.view',
            'fiscal_year.close',
        ],
        'accountant' => [
            'dashboard.view',
            'master_data.view',
            'coa.view',
            'coa.create',
            'coa.edit',
            'contacts.view',
            'contacts.create',
            'contacts.edit',
            'departments.view',
            'departments.create',
            'departments.edit',
            'projects.view',
            'projects.create',
            'projects.edit',
            'journal.view',
            'journal.create',
            'journal.edit',
            'journal.void',
            'journal.approve',
            'journal.post',
            'reports.view',
            'reports.export',
            'audit.view',
            'fiscal_year.view',
        ],
        'sales' => [
            'dashboard.view',
            'contacts.view',
            'contacts.create',
            'contacts.edit',
            'products.view',
            'departments.view',
            'projects.view',
            'sales.view',
            'sales.create',
            'sales.edit',
            'sales.void',
            'reports.view',
        ],
        'purchasing' => [
            'dashboard.view',
            'contacts.view',
            'contacts.create',
            'contacts.edit',
            'products.view',
            'departments.view',
            'projects.view',
            'purchase.view',
            'purchase.create',
            'purchase.edit',
            'purchase.void',
            'reports.view',
        ],
        'warehouse' => [
            'dashboard.view',
            'products.view',
            'units.view',
            'warehouses.view',
            'departments.view',
            'projects.view',
            'inventory.view',
            'inventory.manage',
            'inventory.adjustment.create',
            'inventory.adjustment.edit',
            'inventory.adjustment.void',
            'inventory.transfer',
            'inventory.stock_opname',
            'reports.view',
        ],
        'viewer' => [
            'dashboard.view',
            'reports.view',
            'fiscal_year.view',
        ],
    ],
];
